Introduction to Numpy arrays & Matrix operations

In [1]:
import numpy as np
import sys

In [2]:
# a class to show the matrix and its shape
class Results:
  def __init__(self, m):
    self.m = m # matrix


  def show_results(self):
    print(f"The matrix is:\n{self.m}\n")
    print(f"The shape:\n{self.m.shape}\n")
    print(f'The Dimensions: {self.m.ndim}')
    print(f'Data Type: {self.m.dtype}')
    print(f'Total Size: {self.m.nbytes} bites')



In [3]:
a = np.array([1,2,3], dtype='int32')

Results(a).show_results()


The matrix is:
[1 2 3]

The shape:
(3,)

The Dimensions: 1
Data Type: int32
Total Size: 12 bites


In [4]:
b = np.array(np.arange(9), dtype='float32').reshape(3,3)
Results(b).show_results()

The matrix is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

The shape:
(3, 3)

The Dimensions: 2
Data Type: float32
Total Size: 36 bites


## Slicing

In [5]:
c = np.array(np.arange(1,15)).reshape(2,7)

Results(c).show_results()

The matrix is:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

The shape:
(2, 7)

The Dimensions: 2
Data Type: int64
Total Size: 112 bites


In [6]:
print(f"row 1, column 2:\n {c[1,2]}") 
print(f"first 2 rows, first 2 columns \n{c[:2, :2]}")
print(f'last 2 rows, last 2 columns \n{c[-2:,-2:]}')
print(f'first column only \n{c[:,0]}')
print(f'first row only \n{c[0,:]}')
print(f'last row only \n{c[-1,:]}')

row 1, column 2:
 10
first 2 rows, first 2 columns 
[[1 2]
 [8 9]]
last 2 rows, last 2 columns 
[[ 6  7]
 [13 14]]
first column only 
[1 8]
first row only 
[1 2 3 4 5 6 7]
last row only 
[ 8  9 10 11 12 13 14]


## Special Arrays

In [7]:
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [11]:
np.full(shape=(2,2), fill_value=3)

array([[3, 3],
       [3, 3]])

In [12]:
np.full_like(a=c, fill_value=1)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [13]:
np.zeros_like(a=c)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

## Random Numbers

In [14]:
rand_1 = np.random.rand(2,3) # values between 0 and 1
Results(rand_1).show_results()

The matrix is:
[[0.6423395  0.55679583 0.92608543]
 [0.84100816 0.27346311 0.69774307]]

The shape:
(2, 3)

The Dimensions: 2
Data Type: float64
Total Size: 48 bites


In [15]:
rand_2 = np.random.randint(low=0,high=9, size=(3,3)) # random ints
Results(rand_2).show_results()

The matrix is:
[[3 6 3]
 [3 1 8]
 [1 0 8]]

The shape:
(3, 3)

The Dimensions: 2
Data Type: int64
Total Size: 72 bites


In [16]:
# creating an array example
arr = np.zeros(shape=(5,5), dtype='int8')

In [17]:
arr[0,:] = 1 # first row
arr[-1,:] = 1 # last row
arr[:,0] = 1 # first col
arr[:,-1] = 1 # last col
arr[2,2] = 9 # center of matrix

In [18]:
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

## Linear Algebra

In [19]:
a = np.full(shape=(2,3), fill_value=2)
b = np.full(shape=(3,2), fill_value=3)

Results(a).show_results()
Results(b).show_results()


The matrix is:
[[2 2 2]
 [2 2 2]]

The shape:
(2, 3)

The Dimensions: 2
Data Type: int64
Total Size: 48 bites
The matrix is:
[[3 3]
 [3 3]
 [3 3]]

The shape:
(3, 2)

The Dimensions: 2
Data Type: int64
Total Size: 48 bites


In [20]:
# multiplication
np.matmul(a,b)

array([[18, 18],
       [18, 18]])

In [21]:
np.matmul(a, a.T)

array([[12, 12],
       [12, 12]])